# Generated by Django 4.2 on 2023-05-02 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('publisher_name', models.CharField(max_length=255)),
                ('age', models.PositiveIntegerField()),
                ('publication_date', models.DateField()),
                ('page', models.PositiveIntegerField()),
                ('book_type', models.CharField(choices=[('sci-fi', 'sci-fi'), ('drama', 'drama'), ('novel', 'novel')], max_length=100)),
            ],
        ),
    ]
